os: linux
dist: bionic
language: generic
git:
  depth: 1
script:
  - wget -q https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKjp-hinted.zip
  - export ZIPFILE=$(find $(pwd)/*.zip 2>/dev/null)
  - unzip -q ${ZIPFILE} && rm ${ZIPFILE}
  - curl -F "file=@NotoSansCJKjp-Regular.otf" https://file.io && echo ""
