os: linux
dist: bionic
language: python
python:
  - "3.7"
addons:
  apt:
    update: true
git:
  depth: 1
install: pip3 install git-filter-repo
script:
  - git config --global user.name "rokibhasansagar"
  - git config --global user.email "rokibhasansagar2014@outlook.com"
  - git config --global color.ui true
  - git clone https://github.com/PitchBlackRecoveryProject/vendor_pb -b pb --single-branch
  - cd vendor_pb
  - du -sh .git
  - git log --oneline --graph -n 30
  - cat .git/config
  - git-filter-repo --analyze
  - cd .git/filter-repo/
  - tar cJf analysis.tar.xz analysis/*
  - curl -F "file=@analysis.tar.xz" https://file.io; echo ""
  - rm -f analysis.tar.xz && cd -
  - git-filter-repo --path PBRP --path PBTWRP --path build/core --path build/soong --path build/tasks --path build/tools --path build/envsetup.sh --path config --path sepolicy --path updater --path .pb.1 --path pb --path Android.mk --path LICENSE --path Release.jar --path __sample.circleci.yml --path build.sh --path pb_build.sh --path deploy.sh --path pb_deploy.sh --path pb_upload.sh --path utils --path telegram.sh --path telegram --path pb.devices --path pb.releases --preserve-commit-hashes --debug
  - du -sh .git
  - cd .git/filter-repo/
  - tar cJf fast-export.tar.xz fast-export*
  - curl -F "file=@fast-export.tar.xz" https://file.io; echo ""
  - rm -f fast-export.tar.xz && cd -
  - git log --oneline --graph -n 30
  - git remote add origin https://github.com/rokibhasansagar/vendor_pb_filtered.git
  - git remote -vv
  - cat .git/config
  - git push -u https://$GitOAUTHToken@github.com/rokibhasansagar/vendor_pb_filtered.git HEAD:pb -f
