os: linux
dist: bionic
language: python
python:
  - "3.7"
addons:
  apt:
    update: true
sudo: required
git:
  depth: 1
install: pip3 install git-filter-repo
script:
  - git config --global user.name "rokibhasansagar"
  - git config --global user.email "rokibhasansagar2014@outlook.com"
  - git clone https://github.com/rokibhasansagar/vendor_pb_single.git -b pb --single-branch
  - cd vendor_pb_single
  - git remote add omni https://github.com/omnirom/android_vendor_omni
  - git log --oneline --graph -n 5
  - git fetch omni android-9.0
  - git checkout omni/android-9.0 -- config build/tools build/core build/soong build/tasks sepolicy
  - git add -A .
  - git commit -m "Specific folder merge"
  - git push -f -u https://$GitOAUTHToken@github.com/rokibhasansagar/vendor_pb_single.git HEAD:merged
