os: linux
dist: bionic
language: python
python:
  - "3.7"
addons:
  apt:
    update: true
sudo: required
git:
  depth: 1
install: pip3 install git-filter-repo
script:
  - git config --global user.name "rokibhasansagar"
  - git config --global user.email "rokibhasansagar2014@outlook.com"
  - git clone https://github.com/rokibhasansagar/vendor_pb_single.git -b pb
  - cd vendor_pb_single
  - git remote add omni https://github.com/omnirom/android_vendor_omni
  - git pull -v --ff --allow-unrelated-history -Xresolve omni android-9.0
  - git log --oneline --graph -n 30
