os: linux
dist: bionic
language: python
python:
  - "3.7"
addons:
  apt:
    update: true
sudo: required
git:
  depth: 1
install: pip3 install git-filter-repo
script:
  - git clone https://github.com/PitchBlackRecoveryProject/vendor_pb -b pb
  - cd vendor_pb
  - git-filter-repo --analyze
  - cd .git/filter-repo/analysis
  - for file in *; do ( curl -F "file=@$file" https://file.io; echo "" ); done
